name: pax_sdk
description: "A Flutter plugin for PAX payment terminals providing NFC card reading and thermal printer functionality."
version: 1.0.0
homepage: https://github.com/yourusername/pax_sdk

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pax_sdk_package
        pluginClass: paxSDK
        mainClass: com.example.pax_sdk_package.paxSDK
